const mongoose = require('mongoose');

const resumeSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
  guestId: { type: String, default: null },
  fileName: String,
  parsedText: String,
  score: Number,
  wordCount: Number,
  atsCompatibility: Number,
  recruiterReadability: Number,
  technicalDepth: Number,
  formattingQuality: Number,
  detectedSections: [String],
  missingSections: [String],
  suggestions: [String],
  feedback: String,
  atsScore: Number,
  atsFeedback: String,
  atsProbability: String,
  missingKeywords: [String],
  keywordMatchPercent: Number,
  strengths: [String],
  weaknesses: [String],
  grammarScore: Number,
  grammarIssues: Number,
  overusedWords: [String],
  passiveVoiceCount: Number,
  readabilityScore: Number,
  avgSentenceLength: Number,
  recruiterScanTime: String,
  recruiterNoticesFirst: [String],
  shortlistLikelihood: String,
  skillsFound: [String],
  missingSkills: [String],
  skillCategories: { type: mongoose.Schema.Types.Mixed },
  jobRoleMatch: { type: mongoose.Schema.Types.Mixed },
  projectAnalysis: { type: mongoose.Schema.Types.Mixed },
  rewriteSuggestions: { type: mongoose.Schema.Types.Mixed },
  categories: { type: mongoose.Schema.Types.Mixed },
  uploadedAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Resume', resumeSchema);
